[package]
name = "rust_build"
version = "0.1.0"
authors = ["sun"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# url_serde = "0.2.0"
url = { version = "2.0", features = ["serde"] }
dirs = "3.0.1"
git2 = "0.13.12"
cmd_lib = "0.8.5"
